title: "Huimin"
description: "代码是思考的外化，简洁是智慧的结晶。"
baseurl: ""
url: "https://huimin-z.github.io"
author: Huimin

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 自定义变量
github_username: huimin-z
